// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.1
// source: proto/agent.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Heartbeat message sent from Agent (Data Plane) to Centro (Control Plane)
type HeartbeatRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	NodeId            string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Timestamp         int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	AvailableMemoryMb float32                `protobuf:"fixed32,3,opt,name=available_memory_mb,json=availableMemoryMb,proto3" json:"available_memory_mb,omitempty"`                                                        // Available RAM in MB
	AvailableCpuCores float32                `protobuf:"fixed32,4,opt,name=available_cpu_cores,json=availableCpuCores,proto3" json:"available_cpu_cores,omitempty"`                                                        // Available CPU in cores (e.g., 4.0 = 4 cores, 2.5 = 2.5 cores)
	AvailableDiskMb   float32                `protobuf:"fixed32,5,opt,name=available_disk_mb,json=availableDiskMb,proto3" json:"available_disk_mb,omitempty"`                                                              // Available disk space in MB
	NodeMetadata      map[string]string      `protobuf:"bytes,6,rep,name=node_metadata,json=nodeMetadata,proto3" json:"node_metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional node metadata
	ClusterName       string                 `protobuf:"bytes,7,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`                                                                              // Cluster this node belongs to
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{0}
}

func (x *HeartbeatRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HeartbeatRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HeartbeatRequest) GetAvailableMemoryMb() float32 {
	if x != nil {
		return x.AvailableMemoryMb
	}
	return 0
}

func (x *HeartbeatRequest) GetAvailableCpuCores() float32 {
	if x != nil {
		return x.AvailableCpuCores
	}
	return 0
}

func (x *HeartbeatRequest) GetAvailableDiskMb() float32 {
	if x != nil {
		return x.AvailableDiskMb
	}
	return 0
}

func (x *HeartbeatRequest) GetNodeMetadata() map[string]string {
	if x != nil {
		return x.NodeMetadata
	}
	return nil
}

func (x *HeartbeatRequest) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

type HeartbeatResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged    bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	ResponseMessage string                 `protobuf:"bytes,2,opt,name=response_message,json=responseMessage,proto3" json:"response_message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_proto_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{1}
}

func (x *HeartbeatResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *HeartbeatResponse) GetResponseMessage() string {
	if x != nil {
		return x.ResponseMessage
	}
	return ""
}

// Request from Agent to get an available job from Centro
type GetJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobRequest) Reset() {
	*x = GetJobRequest{}
	mi := &file_proto_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobRequest) ProtoMessage() {}

func (x *GetJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobRequest.ProtoReflect.Descriptor instead.
func (*GetJobRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{2}
}

func (x *GetJobRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

// Job specification - simplified model where each job runs exactly one container
type Job struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	JobId            string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	JobName          string                 `protobuf:"bytes,2,opt,name=job_name,json=jobName,proto3" json:"job_name,omitempty"`
	JobType          string                 `protobuf:"bytes,3,opt,name=job_type,json=jobType,proto3" json:"job_type,omitempty"`                            // Job type: "service", "batch", etc.
	SelectedClusters []string               `protobuf:"bytes,4,rep,name=selected_clusters,json=selectedClusters,proto3" json:"selected_clusters,omitempty"` // Clusters where this job can run (empty = any cluster)
	// Job execution configuration (merged from Task)
	DriverType           string            `protobuf:"bytes,5,opt,name=driver_type,json=driverType,proto3" json:"driver_type,omitempty"` // Driver type: "podman", "incus", "exec"
	Command              string            `protobuf:"bytes,6,opt,name=command,proto3" json:"command,omitempty"`                         // Command or script to execute
	ContainerConfig      *ContainerSpec    `protobuf:"bytes,7,opt,name=container_config,json=containerConfig,proto3" json:"container_config,omitempty"`
	EnvironmentVariables map[string]string `protobuf:"bytes,8,rep,name=environment_variables,json=environmentVariables,proto3" json:"environment_variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ResourceRequirements *Resources        `protobuf:"bytes,9,opt,name=resource_requirements,json=resourceRequirements,proto3" json:"resource_requirements,omitempty"`
	VolumeMounts         []*Volume         `protobuf:"bytes,10,rep,name=volume_mounts,json=volumeMounts,proto3" json:"volume_mounts,omitempty"`
	WorkloadType         string            `protobuf:"bytes,11,opt,name=workload_type,json=workloadType,proto3" json:"workload_type,omitempty"`                                                                        // Workload type: "container", "vm", "process"
	JobMetadata          map[string]string `protobuf:"bytes,12,rep,name=job_metadata,json=jobMetadata,proto3" json:"job_metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Job-level metadata
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_proto_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{3}
}

func (x *Job) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *Job) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

func (x *Job) GetJobType() string {
	if x != nil {
		return x.JobType
	}
	return ""
}

func (x *Job) GetSelectedClusters() []string {
	if x != nil {
		return x.SelectedClusters
	}
	return nil
}

func (x *Job) GetDriverType() string {
	if x != nil {
		return x.DriverType
	}
	return ""
}

func (x *Job) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *Job) GetContainerConfig() *ContainerSpec {
	if x != nil {
		return x.ContainerConfig
	}
	return nil
}

func (x *Job) GetEnvironmentVariables() map[string]string {
	if x != nil {
		return x.EnvironmentVariables
	}
	return nil
}

func (x *Job) GetResourceRequirements() *Resources {
	if x != nil {
		return x.ResourceRequirements
	}
	return nil
}

func (x *Job) GetVolumeMounts() []*Volume {
	if x != nil {
		return x.VolumeMounts
	}
	return nil
}

func (x *Job) GetWorkloadType() string {
	if x != nil {
		return x.WorkloadType
	}
	return ""
}

func (x *Job) GetJobMetadata() map[string]string {
	if x != nil {
		return x.JobMetadata
	}
	return nil
}

// Resource requirements and limits for job execution
type Resources struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MemoryLimitMb    int64                  `protobuf:"varint,1,opt,name=memory_limit_mb,json=memoryLimitMb,proto3" json:"memory_limit_mb,omitempty"`           // Maximum memory in MB
	MemoryReservedMb int64                  `protobuf:"varint,2,opt,name=memory_reserved_mb,json=memoryReservedMb,proto3" json:"memory_reserved_mb,omitempty"`  // Reserved/guaranteed memory in MB
	CpuLimitCores    float32                `protobuf:"fixed32,3,opt,name=cpu_limit_cores,json=cpuLimitCores,proto3" json:"cpu_limit_cores,omitempty"`          // CPU limit in cores (e.g., 1.0 = 1 core, 0.5 = half core)
	CpuReservedCores float32                `protobuf:"fixed32,4,opt,name=cpu_reserved_cores,json=cpuReservedCores,proto3" json:"cpu_reserved_cores,omitempty"` // Reserved/guaranteed CPU in cores
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Resources) Reset() {
	*x = Resources{}
	mi := &file_proto_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resources) ProtoMessage() {}

func (x *Resources) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resources.ProtoReflect.Descriptor instead.
func (*Resources) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{4}
}

func (x *Resources) GetMemoryLimitMb() int64 {
	if x != nil {
		return x.MemoryLimitMb
	}
	return 0
}

func (x *Resources) GetMemoryReservedMb() int64 {
	if x != nil {
		return x.MemoryReservedMb
	}
	return 0
}

func (x *Resources) GetCpuLimitCores() float32 {
	if x != nil {
		return x.CpuLimitCores
	}
	return 0
}

func (x *Resources) GetCpuReservedCores() float32 {
	if x != nil {
		return x.CpuReservedCores
	}
	return 0
}

// Volume mount specification for binding host paths to container/VM paths
type Volume struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourcePath    string                 `protobuf:"bytes,1,opt,name=source_path,json=sourcePath,proto3" json:"source_path,omitempty"` // Path on the host system
	TargetPath    string                 `protobuf:"bytes,2,opt,name=target_path,json=targetPath,proto3" json:"target_path,omitempty"` // Path inside the container/VM
	ReadOnly      bool                   `protobuf:"varint,3,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`      // Whether the mount is read-only
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Volume) Reset() {
	*x = Volume{}
	mi := &file_proto_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Volume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Volume) ProtoMessage() {}

func (x *Volume) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Volume.ProtoReflect.Descriptor instead.
func (*Volume) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{5}
}

func (x *Volume) GetSourcePath() string {
	if x != nil {
		return x.SourcePath
	}
	return ""
}

func (x *Volume) GetTargetPath() string {
	if x != nil {
		return x.TargetPath
	}
	return ""
}

func (x *Volume) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

// Container/image specification for containerized workloads
type ContainerSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageName     string                 `protobuf:"bytes,1,opt,name=image_name,json=imageName,proto3" json:"image_name,omitempty"`                                                                                       // Container image (e.g., "nginx:latest")
	Entrypoint    []string               `protobuf:"bytes,2,rep,name=entrypoint,proto3" json:"entrypoint,omitempty"`                                                                                                      // Entrypoint command to run in the container
	Arguments     []string               `protobuf:"bytes,3,rep,name=arguments,proto3" json:"arguments,omitempty"`                                                                                                        // Arguments for the entrypoint command
	DriverOptions map[string]string      `protobuf:"bytes,4,rep,name=driver_options,json=driverOptions,proto3" json:"driver_options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Driver-specific configuration options
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerSpec) Reset() {
	*x = ContainerSpec{}
	mi := &file_proto_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerSpec) ProtoMessage() {}

func (x *ContainerSpec) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerSpec.ProtoReflect.Descriptor instead.
func (*ContainerSpec) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{6}
}

func (x *ContainerSpec) GetImageName() string {
	if x != nil {
		return x.ImageName
	}
	return ""
}

func (x *ContainerSpec) GetEntrypoint() []string {
	if x != nil {
		return x.Entrypoint
	}
	return nil
}

func (x *ContainerSpec) GetArguments() []string {
	if x != nil {
		return x.Arguments
	}
	return nil
}

func (x *ContainerSpec) GetDriverOptions() map[string]string {
	if x != nil {
		return x.DriverOptions
	}
	return nil
}

type GetJobResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	JobAvailable    bool                   `protobuf:"varint,1,opt,name=job_available,json=jobAvailable,proto3" json:"job_available,omitempty"` // Whether a job is available for execution
	Job             *Job                   `protobuf:"bytes,2,opt,name=job,proto3" json:"job,omitempty"`
	ResponseMessage string                 `protobuf:"bytes,3,opt,name=response_message,json=responseMessage,proto3" json:"response_message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetJobResponse) Reset() {
	*x = GetJobResponse{}
	mi := &file_proto_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobResponse) ProtoMessage() {}

func (x *GetJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobResponse.ProtoReflect.Descriptor instead.
func (*GetJobResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{7}
}

func (x *GetJobResponse) GetJobAvailable() bool {
	if x != nil {
		return x.JobAvailable
	}
	return false
}

func (x *GetJobResponse) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

func (x *GetJobResponse) GetResponseMessage() string {
	if x != nil {
		return x.ResponseMessage
	}
	return ""
}

// Status update from Agent to Centro about job execution
type UpdateStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	JobId         string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	JobStatus     string                 `protobuf:"bytes,3,opt,name=job_status,json=jobStatus,proto3" json:"job_status,omitempty"`             // Job status: "pending", "running", "completed", "failed"
	StatusMessage string                 `protobuf:"bytes,4,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"` // Detailed status message or error description
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStatusRequest) Reset() {
	*x = UpdateStatusRequest{}
	mi := &file_proto_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusRequest) ProtoMessage() {}

func (x *UpdateStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateStatusRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *UpdateStatusRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *UpdateStatusRequest) GetJobStatus() string {
	if x != nil {
		return x.JobStatus
	}
	return ""
}

func (x *UpdateStatusRequest) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

func (x *UpdateStatusRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type UpdateStatusResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged    bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	ResponseMessage string                 `protobuf:"bytes,2,opt,name=response_message,json=responseMessage,proto3" json:"response_message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateStatusResponse) Reset() {
	*x = UpdateStatusResponse{}
	mi := &file_proto_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusResponse) ProtoMessage() {}

func (x *UpdateStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateStatusResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *UpdateStatusResponse) GetResponseMessage() string {
	if x != nil {
		return x.ResponseMessage
	}
	return ""
}

// Container inspection data sent from Agent to Centro after container is running
type ContainerData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`                                               // Container ID
	ContainerName string                 `protobuf:"bytes,2,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`                                         // Container name
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`                                                                              // Full image identifier
	ImageName     string                 `protobuf:"bytes,4,opt,name=image_name,json=imageName,proto3" json:"image_name,omitempty"`                                                     // Image name (e.g., "nginx:latest")
	Command       []string               `protobuf:"bytes,5,rep,name=command,proto3" json:"command,omitempty"`                                                                          // Command executed in container
	Args          []string               `protobuf:"bytes,6,rep,name=args,proto3" json:"args,omitempty"`                                                                                // Arguments passed to command
	Created       string                 `protobuf:"bytes,7,opt,name=created,proto3" json:"created,omitempty"`                                                                          // Creation timestamp
	StartedAt     string                 `protobuf:"bytes,8,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`                                                     // Container start timestamp
	FinishedAt    string                 `protobuf:"bytes,9,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`                                                  // Container finish timestamp (if stopped)
	Status        string                 `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`                                                                           // Container status: "running", "stopped", "exited", "failed"
	ExitCode      int32                  `protobuf:"varint,11,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`                                                      // Exit code (if stopped)
	Pid           int32                  `protobuf:"varint,12,opt,name=pid,proto3" json:"pid,omitempty"`                                                                                // Process ID
	Labels        map[string]string      `protobuf:"bytes,13,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Container labels
	Ports         []string               `protobuf:"bytes,14,rep,name=ports,proto3" json:"ports,omitempty"`                                                                             // Exposed ports
	Volumes       []string               `protobuf:"bytes,15,rep,name=volumes,proto3" json:"volumes,omitempty"`                                                                         // Mounted volumes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerData) Reset() {
	*x = ContainerData{}
	mi := &file_proto_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerData) ProtoMessage() {}

func (x *ContainerData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerData.ProtoReflect.Descriptor instead.
func (*ContainerData) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{10}
}

func (x *ContainerData) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *ContainerData) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *ContainerData) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ContainerData) GetImageName() string {
	if x != nil {
		return x.ImageName
	}
	return ""
}

func (x *ContainerData) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *ContainerData) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ContainerData) GetCreated() string {
	if x != nil {
		return x.Created
	}
	return ""
}

func (x *ContainerData) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *ContainerData) GetFinishedAt() string {
	if x != nil {
		return x.FinishedAt
	}
	return ""
}

func (x *ContainerData) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ContainerData) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ContainerData) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ContainerData) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *ContainerData) GetPorts() []string {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *ContainerData) GetVolumes() []string {
	if x != nil {
		return x.Volumes
	}
	return nil
}

type SetContainerDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`                      // Node ID where container is running
	JobId         string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`                         // Job ID associated with the container
	ContainerData *ContainerData         `protobuf:"bytes,3,opt,name=container_data,json=containerData,proto3" json:"container_data,omitempty"` // Container inspection data
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                             // Timestamp when data was collected
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetContainerDataRequest) Reset() {
	*x = SetContainerDataRequest{}
	mi := &file_proto_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetContainerDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetContainerDataRequest) ProtoMessage() {}

func (x *SetContainerDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetContainerDataRequest.ProtoReflect.Descriptor instead.
func (*SetContainerDataRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{11}
}

func (x *SetContainerDataRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *SetContainerDataRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *SetContainerDataRequest) GetContainerData() *ContainerData {
	if x != nil {
		return x.ContainerData
	}
	return nil
}

func (x *SetContainerDataRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type SetContainerDataResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged    bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	ResponseMessage string                 `protobuf:"bytes,2,opt,name=response_message,json=responseMessage,proto3" json:"response_message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SetContainerDataResponse) Reset() {
	*x = SetContainerDataResponse{}
	mi := &file_proto_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetContainerDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetContainerDataResponse) ProtoMessage() {}

func (x *SetContainerDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetContainerDataResponse.ProtoReflect.Descriptor instead.
func (*SetContainerDataResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{12}
}

func (x *SetContainerDataResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *SetContainerDataResponse) GetResponseMessage() string {
	if x != nil {
		return x.ResponseMessage
	}
	return ""
}

var File_proto_agent_proto protoreflect.FileDescriptor

const file_proto_agent_proto_rawDesc = "" +
	"\n" +
	"\x11proto/agent.proto\x12\tscheduler\"\x8d\x03\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12.\n" +
	"\x13available_memory_mb\x18\x03 \x01(\x02R\x11availableMemoryMb\x12.\n" +
	"\x13available_cpu_cores\x18\x04 \x01(\x02R\x11availableCpuCores\x12*\n" +
	"\x11available_disk_mb\x18\x05 \x01(\x02R\x0favailableDiskMb\x12R\n" +
	"\rnode_metadata\x18\x06 \x03(\v2-.scheduler.HeartbeatRequest.NodeMetadataEntryR\fnodeMetadata\x12!\n" +
	"\fcluster_name\x18\a \x01(\tR\vclusterName\x1a?\n" +
	"\x11NodeMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"b\n" +
	"\x11HeartbeatResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x12)\n" +
	"\x10response_message\x18\x02 \x01(\tR\x0fresponseMessage\"(\n" +
	"\rGetJobRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"\xd3\x05\n" +
	"\x03Job\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x19\n" +
	"\bjob_name\x18\x02 \x01(\tR\ajobName\x12\x19\n" +
	"\bjob_type\x18\x03 \x01(\tR\ajobType\x12+\n" +
	"\x11selected_clusters\x18\x04 \x03(\tR\x10selectedClusters\x12\x1f\n" +
	"\vdriver_type\x18\x05 \x01(\tR\n" +
	"driverType\x12\x18\n" +
	"\acommand\x18\x06 \x01(\tR\acommand\x12C\n" +
	"\x10container_config\x18\a \x01(\v2\x18.scheduler.ContainerSpecR\x0fcontainerConfig\x12]\n" +
	"\x15environment_variables\x18\b \x03(\v2(.scheduler.Job.EnvironmentVariablesEntryR\x14environmentVariables\x12I\n" +
	"\x15resource_requirements\x18\t \x01(\v2\x14.scheduler.ResourcesR\x14resourceRequirements\x126\n" +
	"\rvolume_mounts\x18\n" +
	" \x03(\v2\x11.scheduler.VolumeR\fvolumeMounts\x12#\n" +
	"\rworkload_type\x18\v \x01(\tR\fworkloadType\x12B\n" +
	"\fjob_metadata\x18\f \x03(\v2\x1f.scheduler.Job.JobMetadataEntryR\vjobMetadata\x1aG\n" +
	"\x19EnvironmentVariablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10JobMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb7\x01\n" +
	"\tResources\x12&\n" +
	"\x0fmemory_limit_mb\x18\x01 \x01(\x03R\rmemoryLimitMb\x12,\n" +
	"\x12memory_reserved_mb\x18\x02 \x01(\x03R\x10memoryReservedMb\x12&\n" +
	"\x0fcpu_limit_cores\x18\x03 \x01(\x02R\rcpuLimitCores\x12,\n" +
	"\x12cpu_reserved_cores\x18\x04 \x01(\x02R\x10cpuReservedCores\"g\n" +
	"\x06Volume\x12\x1f\n" +
	"\vsource_path\x18\x01 \x01(\tR\n" +
	"sourcePath\x12\x1f\n" +
	"\vtarget_path\x18\x02 \x01(\tR\n" +
	"targetPath\x12\x1b\n" +
	"\tread_only\x18\x03 \x01(\bR\breadOnly\"\x82\x02\n" +
	"\rContainerSpec\x12\x1d\n" +
	"\n" +
	"image_name\x18\x01 \x01(\tR\timageName\x12\x1e\n" +
	"\n" +
	"entrypoint\x18\x02 \x03(\tR\n" +
	"entrypoint\x12\x1c\n" +
	"\targuments\x18\x03 \x03(\tR\targuments\x12R\n" +
	"\x0edriver_options\x18\x04 \x03(\v2+.scheduler.ContainerSpec.DriverOptionsEntryR\rdriverOptions\x1a@\n" +
	"\x12DriverOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x82\x01\n" +
	"\x0eGetJobResponse\x12#\n" +
	"\rjob_available\x18\x01 \x01(\bR\fjobAvailable\x12 \n" +
	"\x03job\x18\x02 \x01(\v2\x0e.scheduler.JobR\x03job\x12)\n" +
	"\x10response_message\x18\x03 \x01(\tR\x0fresponseMessage\"\xa9\x01\n" +
	"\x13UpdateStatusRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12\x1d\n" +
	"\n" +
	"job_status\x18\x03 \x01(\tR\tjobStatus\x12%\n" +
	"\x0estatus_message\x18\x04 \x01(\tR\rstatusMessage\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"e\n" +
	"\x14UpdateStatusResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x12)\n" +
	"\x10response_message\x18\x02 \x01(\tR\x0fresponseMessage\"\x86\x04\n" +
	"\rContainerData\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12%\n" +
	"\x0econtainer_name\x18\x02 \x01(\tR\rcontainerName\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x1d\n" +
	"\n" +
	"image_name\x18\x04 \x01(\tR\timageName\x12\x18\n" +
	"\acommand\x18\x05 \x03(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x06 \x03(\tR\x04args\x12\x18\n" +
	"\acreated\x18\a \x01(\tR\acreated\x12\x1d\n" +
	"\n" +
	"started_at\x18\b \x01(\tR\tstartedAt\x12\x1f\n" +
	"\vfinished_at\x18\t \x01(\tR\n" +
	"finishedAt\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\tR\x06status\x12\x1b\n" +
	"\texit_code\x18\v \x01(\x05R\bexitCode\x12\x10\n" +
	"\x03pid\x18\f \x01(\x05R\x03pid\x12<\n" +
	"\x06labels\x18\r \x03(\v2$.scheduler.ContainerData.LabelsEntryR\x06labels\x12\x14\n" +
	"\x05ports\x18\x0e \x03(\tR\x05ports\x12\x18\n" +
	"\avolumes\x18\x0f \x03(\tR\avolumes\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa8\x01\n" +
	"\x17SetContainerDataRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12?\n" +
	"\x0econtainer_data\x18\x03 \x01(\v2\x18.scheduler.ContainerDataR\rcontainerData\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"i\n" +
	"\x18SetContainerDataResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x12)\n" +
	"\x10response_message\x18\x02 \x01(\tR\x0fresponseMessage2\xcd\x02\n" +
	"\x16CentroSchedulerService\x12F\n" +
	"\tHeartbeat\x12\x1b.scheduler.HeartbeatRequest\x1a\x1c.scheduler.HeartbeatResponse\x12=\n" +
	"\x06GetJob\x12\x18.scheduler.GetJobRequest\x1a\x19.scheduler.GetJobResponse\x12O\n" +
	"\fUpdateStatus\x12\x1e.scheduler.UpdateStatusRequest\x1a\x1f.scheduler.UpdateStatusResponse\x12[\n" +
	"\x10SetContainerData\x12\".scheduler.SetContainerDataRequest\x1a#.scheduler.SetContainerDataResponseB!Z\x1fgithub.com/open-scheduler/protob\x06proto3"

var (
	file_proto_agent_proto_rawDescOnce sync.Once
	file_proto_agent_proto_rawDescData []byte
)

func file_proto_agent_proto_rawDescGZIP() []byte {
	file_proto_agent_proto_rawDescOnce.Do(func() {
		file_proto_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_agent_proto_rawDesc), len(file_proto_agent_proto_rawDesc)))
	})
	return file_proto_agent_proto_rawDescData
}

var file_proto_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_proto_agent_proto_goTypes = []any{
	(*HeartbeatRequest)(nil),         // 0: scheduler.HeartbeatRequest
	(*HeartbeatResponse)(nil),        // 1: scheduler.HeartbeatResponse
	(*GetJobRequest)(nil),            // 2: scheduler.GetJobRequest
	(*Job)(nil),                      // 3: scheduler.Job
	(*Resources)(nil),                // 4: scheduler.Resources
	(*Volume)(nil),                   // 5: scheduler.Volume
	(*ContainerSpec)(nil),            // 6: scheduler.ContainerSpec
	(*GetJobResponse)(nil),           // 7: scheduler.GetJobResponse
	(*UpdateStatusRequest)(nil),      // 8: scheduler.UpdateStatusRequest
	(*UpdateStatusResponse)(nil),     // 9: scheduler.UpdateStatusResponse
	(*ContainerData)(nil),            // 10: scheduler.ContainerData
	(*SetContainerDataRequest)(nil),  // 11: scheduler.SetContainerDataRequest
	(*SetContainerDataResponse)(nil), // 12: scheduler.SetContainerDataResponse
	nil,                              // 13: scheduler.HeartbeatRequest.NodeMetadataEntry
	nil,                              // 14: scheduler.Job.EnvironmentVariablesEntry
	nil,                              // 15: scheduler.Job.JobMetadataEntry
	nil,                              // 16: scheduler.ContainerSpec.DriverOptionsEntry
	nil,                              // 17: scheduler.ContainerData.LabelsEntry
}
var file_proto_agent_proto_depIdxs = []int32{
	13, // 0: scheduler.HeartbeatRequest.node_metadata:type_name -> scheduler.HeartbeatRequest.NodeMetadataEntry
	6,  // 1: scheduler.Job.container_config:type_name -> scheduler.ContainerSpec
	14, // 2: scheduler.Job.environment_variables:type_name -> scheduler.Job.EnvironmentVariablesEntry
	4,  // 3: scheduler.Job.resource_requirements:type_name -> scheduler.Resources
	5,  // 4: scheduler.Job.volume_mounts:type_name -> scheduler.Volume
	15, // 5: scheduler.Job.job_metadata:type_name -> scheduler.Job.JobMetadataEntry
	16, // 6: scheduler.ContainerSpec.driver_options:type_name -> scheduler.ContainerSpec.DriverOptionsEntry
	3,  // 7: scheduler.GetJobResponse.job:type_name -> scheduler.Job
	17, // 8: scheduler.ContainerData.labels:type_name -> scheduler.ContainerData.LabelsEntry
	10, // 9: scheduler.SetContainerDataRequest.container_data:type_name -> scheduler.ContainerData
	0,  // 10: scheduler.CentroSchedulerService.Heartbeat:input_type -> scheduler.HeartbeatRequest
	2,  // 11: scheduler.CentroSchedulerService.GetJob:input_type -> scheduler.GetJobRequest
	8,  // 12: scheduler.CentroSchedulerService.UpdateStatus:input_type -> scheduler.UpdateStatusRequest
	11, // 13: scheduler.CentroSchedulerService.SetContainerData:input_type -> scheduler.SetContainerDataRequest
	1,  // 14: scheduler.CentroSchedulerService.Heartbeat:output_type -> scheduler.HeartbeatResponse
	7,  // 15: scheduler.CentroSchedulerService.GetJob:output_type -> scheduler.GetJobResponse
	9,  // 16: scheduler.CentroSchedulerService.UpdateStatus:output_type -> scheduler.UpdateStatusResponse
	12, // 17: scheduler.CentroSchedulerService.SetContainerData:output_type -> scheduler.SetContainerDataResponse
	14, // [14:18] is the sub-list for method output_type
	10, // [10:14] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_agent_proto_init() }
func file_proto_agent_proto_init() {
	if File_proto_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_agent_proto_rawDesc), len(file_proto_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_agent_proto_goTypes,
		DependencyIndexes: file_proto_agent_proto_depIdxs,
		MessageInfos:      file_proto_agent_proto_msgTypes,
	}.Build()
	File_proto_agent_proto = out.File
	file_proto_agent_proto_goTypes = nil
	file_proto_agent_proto_depIdxs = nil
}
