// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.1
// source: proto/agent.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CentroSchedulerService_Heartbeat_FullMethodName       = "/scheduler.CentroSchedulerService/Heartbeat"
	CentroSchedulerService_GetJob_FullMethodName          = "/scheduler.CentroSchedulerService/GetJob"
	CentroSchedulerService_UpdateStatus_FullMethodName    = "/scheduler.CentroSchedulerService/UpdateStatus"
	CentroSchedulerService_SetInstanceData_FullMethodName = "/scheduler.CentroSchedulerService/SetInstanceData"
)

// CentroSchedulerServiceClient is the client API for CentroSchedulerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service provided by Centro (Control Plane) for Agent (Data Plane) communication
type CentroSchedulerServiceClient interface {
	// Agent sends periodic heartbeat to report node health and available resources
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// Agent requests an available job from Centro for execution
	GetJob(ctx context.Context, in *GetJobRequest, opts ...grpc.CallOption) (*GetJobResponse, error)
	// Agent sends job execution status updates to Centro
	UpdateStatus(ctx context.Context, in *UpdateStatusRequest, opts ...grpc.CallOption) (*UpdateStatusResponse, error)
	// Agent sends instance inspection data after instance is running
	SetInstanceData(ctx context.Context, in *SetInstanceDataRequest, opts ...grpc.CallOption) (*SetInstanceDataResponse, error)
}

type centroSchedulerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCentroSchedulerServiceClient(cc grpc.ClientConnInterface) CentroSchedulerServiceClient {
	return &centroSchedulerServiceClient{cc}
}

func (c *centroSchedulerServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, CentroSchedulerService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *centroSchedulerServiceClient) GetJob(ctx context.Context, in *GetJobRequest, opts ...grpc.CallOption) (*GetJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetJobResponse)
	err := c.cc.Invoke(ctx, CentroSchedulerService_GetJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *centroSchedulerServiceClient) UpdateStatus(ctx context.Context, in *UpdateStatusRequest, opts ...grpc.CallOption) (*UpdateStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateStatusResponse)
	err := c.cc.Invoke(ctx, CentroSchedulerService_UpdateStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *centroSchedulerServiceClient) SetInstanceData(ctx context.Context, in *SetInstanceDataRequest, opts ...grpc.CallOption) (*SetInstanceDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetInstanceDataResponse)
	err := c.cc.Invoke(ctx, CentroSchedulerService_SetInstanceData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CentroSchedulerServiceServer is the server API for CentroSchedulerService service.
// All implementations must embed UnimplementedCentroSchedulerServiceServer
// for forward compatibility.
//
// Service provided by Centro (Control Plane) for Agent (Data Plane) communication
type CentroSchedulerServiceServer interface {
	// Agent sends periodic heartbeat to report node health and available resources
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// Agent requests an available job from Centro for execution
	GetJob(context.Context, *GetJobRequest) (*GetJobResponse, error)
	// Agent sends job execution status updates to Centro
	UpdateStatus(context.Context, *UpdateStatusRequest) (*UpdateStatusResponse, error)
	// Agent sends instance inspection data after instance is running
	SetInstanceData(context.Context, *SetInstanceDataRequest) (*SetInstanceDataResponse, error)
	mustEmbedUnimplementedCentroSchedulerServiceServer()
}

// UnimplementedCentroSchedulerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCentroSchedulerServiceServer struct{}

func (UnimplementedCentroSchedulerServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedCentroSchedulerServiceServer) GetJob(context.Context, *GetJobRequest) (*GetJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJob not implemented")
}
func (UnimplementedCentroSchedulerServiceServer) UpdateStatus(context.Context, *UpdateStatusRequest) (*UpdateStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateStatus not implemented")
}
func (UnimplementedCentroSchedulerServiceServer) SetInstanceData(context.Context, *SetInstanceDataRequest) (*SetInstanceDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetInstanceData not implemented")
}
func (UnimplementedCentroSchedulerServiceServer) mustEmbedUnimplementedCentroSchedulerServiceServer() {
}
func (UnimplementedCentroSchedulerServiceServer) testEmbeddedByValue() {}

// UnsafeCentroSchedulerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CentroSchedulerServiceServer will
// result in compilation errors.
type UnsafeCentroSchedulerServiceServer interface {
	mustEmbedUnimplementedCentroSchedulerServiceServer()
}

func RegisterCentroSchedulerServiceServer(s grpc.ServiceRegistrar, srv CentroSchedulerServiceServer) {
	// If the following call pancis, it indicates UnimplementedCentroSchedulerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CentroSchedulerService_ServiceDesc, srv)
}

func _CentroSchedulerService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CentroSchedulerServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CentroSchedulerService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CentroSchedulerServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CentroSchedulerService_GetJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CentroSchedulerServiceServer).GetJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CentroSchedulerService_GetJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CentroSchedulerServiceServer).GetJob(ctx, req.(*GetJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CentroSchedulerService_UpdateStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CentroSchedulerServiceServer).UpdateStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CentroSchedulerService_UpdateStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CentroSchedulerServiceServer).UpdateStatus(ctx, req.(*UpdateStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CentroSchedulerService_SetInstanceData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetInstanceDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CentroSchedulerServiceServer).SetInstanceData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CentroSchedulerService_SetInstanceData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CentroSchedulerServiceServer).SetInstanceData(ctx, req.(*SetInstanceDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CentroSchedulerService_ServiceDesc is the grpc.ServiceDesc for CentroSchedulerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CentroSchedulerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "scheduler.CentroSchedulerService",
	HandlerType: (*CentroSchedulerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Heartbeat",
			Handler:    _CentroSchedulerService_Heartbeat_Handler,
		},
		{
			MethodName: "GetJob",
			Handler:    _CentroSchedulerService_GetJob_Handler,
		},
		{
			MethodName: "UpdateStatus",
			Handler:    _CentroSchedulerService_UpdateStatus_Handler,
		},
		{
			MethodName: "SetInstanceData",
			Handler:    _CentroSchedulerService_SetInstanceData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/agent.proto",
}
