// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.1
// source: proto/agent.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Heartbeat message sent from Agent (Data Plane) to Centro (Control Plane)
type HeartbeatRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	NodeId            string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Timestamp         int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	AvailableMemoryMb float32                `protobuf:"fixed32,3,opt,name=available_memory_mb,json=availableMemoryMb,proto3" json:"available_memory_mb,omitempty"`                                                        // Available RAM in MB
	AvailableCpuCores float32                `protobuf:"fixed32,4,opt,name=available_cpu_cores,json=availableCpuCores,proto3" json:"available_cpu_cores,omitempty"`                                                        // Available CPU in cores (e.g., 4.0 = 4 cores, 2.5 = 2.5 cores)
	AvailableDiskMb   float32                `protobuf:"fixed32,5,opt,name=available_disk_mb,json=availableDiskMb,proto3" json:"available_disk_mb,omitempty"`                                                              // Available disk space in MB
	NodeMetadata      map[string]string      `protobuf:"bytes,6,rep,name=node_metadata,json=nodeMetadata,proto3" json:"node_metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional node metadata
	ClusterName       string                 `protobuf:"bytes,7,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`                                                                              // Cluster this node belongs to
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{0}
}

func (x *HeartbeatRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HeartbeatRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HeartbeatRequest) GetAvailableMemoryMb() float32 {
	if x != nil {
		return x.AvailableMemoryMb
	}
	return 0
}

func (x *HeartbeatRequest) GetAvailableCpuCores() float32 {
	if x != nil {
		return x.AvailableCpuCores
	}
	return 0
}

func (x *HeartbeatRequest) GetAvailableDiskMb() float32 {
	if x != nil {
		return x.AvailableDiskMb
	}
	return 0
}

func (x *HeartbeatRequest) GetNodeMetadata() map[string]string {
	if x != nil {
		return x.NodeMetadata
	}
	return nil
}

func (x *HeartbeatRequest) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

type HeartbeatResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged    bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	ResponseMessage string                 `protobuf:"bytes,2,opt,name=response_message,json=responseMessage,proto3" json:"response_message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_proto_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{1}
}

func (x *HeartbeatResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *HeartbeatResponse) GetResponseMessage() string {
	if x != nil {
		return x.ResponseMessage
	}
	return ""
}

// Request from Agent to get an available job from Centro
type GetJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobRequest) Reset() {
	*x = GetJobRequest{}
	mi := &file_proto_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobRequest) ProtoMessage() {}

func (x *GetJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobRequest.ProtoReflect.Descriptor instead.
func (*GetJobRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{2}
}

func (x *GetJobRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

// Job specification, inspired by Nomad job spec (simplified)
type Job struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	JobId            string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	JobName          string                 `protobuf:"bytes,2,opt,name=job_name,json=jobName,proto3" json:"job_name,omitempty"`
	JobType          string                 `protobuf:"bytes,3,opt,name=job_type,json=jobType,proto3" json:"job_type,omitempty"`                            // Job type: "service", "batch", etc.
	SelectedClusters []string               `protobuf:"bytes,4,rep,name=selected_clusters,json=selectedClusters,proto3" json:"selected_clusters,omitempty"` // Clusters where this job can run (empty = any cluster)
	Tasks            []*Task                `protobuf:"bytes,5,rep,name=tasks,proto3" json:"tasks,omitempty"`
	JobMetadata      map[string]string      `protobuf:"bytes,6,rep,name=job_metadata,json=jobMetadata,proto3" json:"job_metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Job-level metadata
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_proto_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{3}
}

func (x *Job) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *Job) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

func (x *Job) GetJobType() string {
	if x != nil {
		return x.JobType
	}
	return ""
}

func (x *Job) GetSelectedClusters() []string {
	if x != nil {
		return x.SelectedClusters
	}
	return nil
}

func (x *Job) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *Job) GetJobMetadata() map[string]string {
	if x != nil {
		return x.JobMetadata
	}
	return nil
}

type Task struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	TaskName             string                 `protobuf:"bytes,1,opt,name=task_name,json=taskName,proto3" json:"task_name,omitempty"`
	DriverType           string                 `protobuf:"bytes,2,opt,name=driver_type,json=driverType,proto3" json:"driver_type,omitempty"` // Driver type: "podman", "incus", "exec"
	Command              string                 `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`                         // Command or script to execute
	ContainerConfig      *ContainerSpec         `protobuf:"bytes,4,opt,name=container_config,json=containerConfig,proto3" json:"container_config,omitempty"`
	EnvironmentVariables map[string]string      `protobuf:"bytes,5,rep,name=environment_variables,json=environmentVariables,proto3" json:"environment_variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ResourceRequirements *Resources             `protobuf:"bytes,6,opt,name=resource_requirements,json=resourceRequirements,proto3" json:"resource_requirements,omitempty"`
	VolumeMounts         []*Volume              `protobuf:"bytes,7,rep,name=volume_mounts,json=volumeMounts,proto3" json:"volume_mounts,omitempty"`
	WorkloadType         string                 `protobuf:"bytes,8,opt,name=workload_type,json=workloadType,proto3" json:"workload_type,omitempty"` // Workload type: "container", "vm", "process"
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_proto_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{4}
}

func (x *Task) GetTaskName() string {
	if x != nil {
		return x.TaskName
	}
	return ""
}

func (x *Task) GetDriverType() string {
	if x != nil {
		return x.DriverType
	}
	return ""
}

func (x *Task) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *Task) GetContainerConfig() *ContainerSpec {
	if x != nil {
		return x.ContainerConfig
	}
	return nil
}

func (x *Task) GetEnvironmentVariables() map[string]string {
	if x != nil {
		return x.EnvironmentVariables
	}
	return nil
}

func (x *Task) GetResourceRequirements() *Resources {
	if x != nil {
		return x.ResourceRequirements
	}
	return nil
}

func (x *Task) GetVolumeMounts() []*Volume {
	if x != nil {
		return x.VolumeMounts
	}
	return nil
}

func (x *Task) GetWorkloadType() string {
	if x != nil {
		return x.WorkloadType
	}
	return ""
}

// Resource requirements and limits for task execution
type Resources struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MemoryLimitMb    int64                  `protobuf:"varint,1,opt,name=memory_limit_mb,json=memoryLimitMb,proto3" json:"memory_limit_mb,omitempty"`           // Maximum memory in MB
	MemoryReservedMb int64                  `protobuf:"varint,2,opt,name=memory_reserved_mb,json=memoryReservedMb,proto3" json:"memory_reserved_mb,omitempty"`  // Reserved/guaranteed memory in MB
	CpuLimitCores    float32                `protobuf:"fixed32,3,opt,name=cpu_limit_cores,json=cpuLimitCores,proto3" json:"cpu_limit_cores,omitempty"`          // CPU limit in cores (e.g., 1.0 = 1 core, 0.5 = half core)
	CpuReservedCores float32                `protobuf:"fixed32,4,opt,name=cpu_reserved_cores,json=cpuReservedCores,proto3" json:"cpu_reserved_cores,omitempty"` // Reserved/guaranteed CPU in cores
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Resources) Reset() {
	*x = Resources{}
	mi := &file_proto_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resources) ProtoMessage() {}

func (x *Resources) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resources.ProtoReflect.Descriptor instead.
func (*Resources) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{5}
}

func (x *Resources) GetMemoryLimitMb() int64 {
	if x != nil {
		return x.MemoryLimitMb
	}
	return 0
}

func (x *Resources) GetMemoryReservedMb() int64 {
	if x != nil {
		return x.MemoryReservedMb
	}
	return 0
}

func (x *Resources) GetCpuLimitCores() float32 {
	if x != nil {
		return x.CpuLimitCores
	}
	return 0
}

func (x *Resources) GetCpuReservedCores() float32 {
	if x != nil {
		return x.CpuReservedCores
	}
	return 0
}

// Volume mount specification for binding host paths to container/VM paths
type Volume struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourcePath    string                 `protobuf:"bytes,1,opt,name=source_path,json=sourcePath,proto3" json:"source_path,omitempty"` // Path on the host system
	TargetPath    string                 `protobuf:"bytes,2,opt,name=target_path,json=targetPath,proto3" json:"target_path,omitempty"` // Path inside the container/VM
	ReadOnly      bool                   `protobuf:"varint,3,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`      // Whether the mount is read-only
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Volume) Reset() {
	*x = Volume{}
	mi := &file_proto_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Volume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Volume) ProtoMessage() {}

func (x *Volume) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Volume.ProtoReflect.Descriptor instead.
func (*Volume) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{6}
}

func (x *Volume) GetSourcePath() string {
	if x != nil {
		return x.SourcePath
	}
	return ""
}

func (x *Volume) GetTargetPath() string {
	if x != nil {
		return x.TargetPath
	}
	return ""
}

func (x *Volume) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

// Container/image specification for containerized workloads
type ContainerSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageName     string                 `protobuf:"bytes,1,opt,name=image_name,json=imageName,proto3" json:"image_name,omitempty"`                                                                                       // Container image (e.g., "nginx:latest")
	Entrypoint    []string               `protobuf:"bytes,2,rep,name=entrypoint,proto3" json:"entrypoint,omitempty"`                                                                                                      // Entrypoint command to run in the container
	Arguments     []string               `protobuf:"bytes,3,rep,name=arguments,proto3" json:"arguments,omitempty"`                                                                                                        // Arguments for the entrypoint command
	DriverOptions map[string]string      `protobuf:"bytes,4,rep,name=driver_options,json=driverOptions,proto3" json:"driver_options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Driver-specific configuration options
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerSpec) Reset() {
	*x = ContainerSpec{}
	mi := &file_proto_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerSpec) ProtoMessage() {}

func (x *ContainerSpec) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerSpec.ProtoReflect.Descriptor instead.
func (*ContainerSpec) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{7}
}

func (x *ContainerSpec) GetImageName() string {
	if x != nil {
		return x.ImageName
	}
	return ""
}

func (x *ContainerSpec) GetEntrypoint() []string {
	if x != nil {
		return x.Entrypoint
	}
	return nil
}

func (x *ContainerSpec) GetArguments() []string {
	if x != nil {
		return x.Arguments
	}
	return nil
}

func (x *ContainerSpec) GetDriverOptions() map[string]string {
	if x != nil {
		return x.DriverOptions
	}
	return nil
}

type GetJobResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	JobAvailable    bool                   `protobuf:"varint,1,opt,name=job_available,json=jobAvailable,proto3" json:"job_available,omitempty"` // Whether a job is available for execution
	Job             *Job                   `protobuf:"bytes,2,opt,name=job,proto3" json:"job,omitempty"`
	ResponseMessage string                 `protobuf:"bytes,3,opt,name=response_message,json=responseMessage,proto3" json:"response_message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetJobResponse) Reset() {
	*x = GetJobResponse{}
	mi := &file_proto_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobResponse) ProtoMessage() {}

func (x *GetJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobResponse.ProtoReflect.Descriptor instead.
func (*GetJobResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{8}
}

func (x *GetJobResponse) GetJobAvailable() bool {
	if x != nil {
		return x.JobAvailable
	}
	return false
}

func (x *GetJobResponse) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

func (x *GetJobResponse) GetResponseMessage() string {
	if x != nil {
		return x.ResponseMessage
	}
	return ""
}

// Status update from Agent to Centro about job execution
type UpdateStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	JobId         string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	JobStatus     string                 `protobuf:"bytes,3,opt,name=job_status,json=jobStatus,proto3" json:"job_status,omitempty"`             // Job status: "pending", "running", "completed", "failed"
	StatusMessage string                 `protobuf:"bytes,4,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"` // Detailed status message or error description
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStatusRequest) Reset() {
	*x = UpdateStatusRequest{}
	mi := &file_proto_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusRequest) ProtoMessage() {}

func (x *UpdateStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateStatusRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *UpdateStatusRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *UpdateStatusRequest) GetJobStatus() string {
	if x != nil {
		return x.JobStatus
	}
	return ""
}

func (x *UpdateStatusRequest) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

func (x *UpdateStatusRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type UpdateStatusResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged    bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	ResponseMessage string                 `protobuf:"bytes,2,opt,name=response_message,json=responseMessage,proto3" json:"response_message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateStatusResponse) Reset() {
	*x = UpdateStatusResponse{}
	mi := &file_proto_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusResponse) ProtoMessage() {}

func (x *UpdateStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateStatusResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *UpdateStatusResponse) GetResponseMessage() string {
	if x != nil {
		return x.ResponseMessage
	}
	return ""
}

var File_proto_agent_proto protoreflect.FileDescriptor

const file_proto_agent_proto_rawDesc = "" +
	"\n" +
	"\x11proto/agent.proto\x12\tscheduler\"\x8d\x03\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12.\n" +
	"\x13available_memory_mb\x18\x03 \x01(\x02R\x11availableMemoryMb\x12.\n" +
	"\x13available_cpu_cores\x18\x04 \x01(\x02R\x11availableCpuCores\x12*\n" +
	"\x11available_disk_mb\x18\x05 \x01(\x02R\x0favailableDiskMb\x12R\n" +
	"\rnode_metadata\x18\x06 \x03(\v2-.scheduler.HeartbeatRequest.NodeMetadataEntryR\fnodeMetadata\x12!\n" +
	"\fcluster_name\x18\a \x01(\tR\vclusterName\x1a?\n" +
	"\x11NodeMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"b\n" +
	"\x11HeartbeatResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x12)\n" +
	"\x10response_message\x18\x02 \x01(\tR\x0fresponseMessage\"(\n" +
	"\rGetJobRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"\xaa\x02\n" +
	"\x03Job\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x19\n" +
	"\bjob_name\x18\x02 \x01(\tR\ajobName\x12\x19\n" +
	"\bjob_type\x18\x03 \x01(\tR\ajobType\x12+\n" +
	"\x11selected_clusters\x18\x04 \x03(\tR\x10selectedClusters\x12%\n" +
	"\x05tasks\x18\x05 \x03(\v2\x0f.scheduler.TaskR\x05tasks\x12B\n" +
	"\fjob_metadata\x18\x06 \x03(\v2\x1f.scheduler.Job.JobMetadataEntryR\vjobMetadata\x1a>\n" +
	"\x10JobMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf4\x03\n" +
	"\x04Task\x12\x1b\n" +
	"\ttask_name\x18\x01 \x01(\tR\btaskName\x12\x1f\n" +
	"\vdriver_type\x18\x02 \x01(\tR\n" +
	"driverType\x12\x18\n" +
	"\acommand\x18\x03 \x01(\tR\acommand\x12C\n" +
	"\x10container_config\x18\x04 \x01(\v2\x18.scheduler.ContainerSpecR\x0fcontainerConfig\x12^\n" +
	"\x15environment_variables\x18\x05 \x03(\v2).scheduler.Task.EnvironmentVariablesEntryR\x14environmentVariables\x12I\n" +
	"\x15resource_requirements\x18\x06 \x01(\v2\x14.scheduler.ResourcesR\x14resourceRequirements\x126\n" +
	"\rvolume_mounts\x18\a \x03(\v2\x11.scheduler.VolumeR\fvolumeMounts\x12#\n" +
	"\rworkload_type\x18\b \x01(\tR\fworkloadType\x1aG\n" +
	"\x19EnvironmentVariablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb7\x01\n" +
	"\tResources\x12&\n" +
	"\x0fmemory_limit_mb\x18\x01 \x01(\x03R\rmemoryLimitMb\x12,\n" +
	"\x12memory_reserved_mb\x18\x02 \x01(\x03R\x10memoryReservedMb\x12&\n" +
	"\x0fcpu_limit_cores\x18\x03 \x01(\x02R\rcpuLimitCores\x12,\n" +
	"\x12cpu_reserved_cores\x18\x04 \x01(\x02R\x10cpuReservedCores\"g\n" +
	"\x06Volume\x12\x1f\n" +
	"\vsource_path\x18\x01 \x01(\tR\n" +
	"sourcePath\x12\x1f\n" +
	"\vtarget_path\x18\x02 \x01(\tR\n" +
	"targetPath\x12\x1b\n" +
	"\tread_only\x18\x03 \x01(\bR\breadOnly\"\x82\x02\n" +
	"\rContainerSpec\x12\x1d\n" +
	"\n" +
	"image_name\x18\x01 \x01(\tR\timageName\x12\x1e\n" +
	"\n" +
	"entrypoint\x18\x02 \x03(\tR\n" +
	"entrypoint\x12\x1c\n" +
	"\targuments\x18\x03 \x03(\tR\targuments\x12R\n" +
	"\x0edriver_options\x18\x04 \x03(\v2+.scheduler.ContainerSpec.DriverOptionsEntryR\rdriverOptions\x1a@\n" +
	"\x12DriverOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x82\x01\n" +
	"\x0eGetJobResponse\x12#\n" +
	"\rjob_available\x18\x01 \x01(\bR\fjobAvailable\x12 \n" +
	"\x03job\x18\x02 \x01(\v2\x0e.scheduler.JobR\x03job\x12)\n" +
	"\x10response_message\x18\x03 \x01(\tR\x0fresponseMessage\"\xa9\x01\n" +
	"\x13UpdateStatusRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12\x1d\n" +
	"\n" +
	"job_status\x18\x03 \x01(\tR\tjobStatus\x12%\n" +
	"\x0estatus_message\x18\x04 \x01(\tR\rstatusMessage\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"e\n" +
	"\x14UpdateStatusResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x12)\n" +
	"\x10response_message\x18\x02 \x01(\tR\x0fresponseMessage2\xf0\x01\n" +
	"\x16CentroSchedulerService\x12F\n" +
	"\tHeartbeat\x12\x1b.scheduler.HeartbeatRequest\x1a\x1c.scheduler.HeartbeatResponse\x12=\n" +
	"\x06GetJob\x12\x18.scheduler.GetJobRequest\x1a\x19.scheduler.GetJobResponse\x12O\n" +
	"\fUpdateStatus\x12\x1e.scheduler.UpdateStatusRequest\x1a\x1f.scheduler.UpdateStatusResponseB!Z\x1fgithub.com/open-scheduler/protob\x06proto3"

var (
	file_proto_agent_proto_rawDescOnce sync.Once
	file_proto_agent_proto_rawDescData []byte
)

func file_proto_agent_proto_rawDescGZIP() []byte {
	file_proto_agent_proto_rawDescOnce.Do(func() {
		file_proto_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_agent_proto_rawDesc), len(file_proto_agent_proto_rawDesc)))
	})
	return file_proto_agent_proto_rawDescData
}

var file_proto_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_agent_proto_goTypes = []any{
	(*HeartbeatRequest)(nil),     // 0: scheduler.HeartbeatRequest
	(*HeartbeatResponse)(nil),    // 1: scheduler.HeartbeatResponse
	(*GetJobRequest)(nil),        // 2: scheduler.GetJobRequest
	(*Job)(nil),                  // 3: scheduler.Job
	(*Task)(nil),                 // 4: scheduler.Task
	(*Resources)(nil),            // 5: scheduler.Resources
	(*Volume)(nil),               // 6: scheduler.Volume
	(*ContainerSpec)(nil),        // 7: scheduler.ContainerSpec
	(*GetJobResponse)(nil),       // 8: scheduler.GetJobResponse
	(*UpdateStatusRequest)(nil),  // 9: scheduler.UpdateStatusRequest
	(*UpdateStatusResponse)(nil), // 10: scheduler.UpdateStatusResponse
	nil,                          // 11: scheduler.HeartbeatRequest.NodeMetadataEntry
	nil,                          // 12: scheduler.Job.JobMetadataEntry
	nil,                          // 13: scheduler.Task.EnvironmentVariablesEntry
	nil,                          // 14: scheduler.ContainerSpec.DriverOptionsEntry
}
var file_proto_agent_proto_depIdxs = []int32{
	11, // 0: scheduler.HeartbeatRequest.node_metadata:type_name -> scheduler.HeartbeatRequest.NodeMetadataEntry
	4,  // 1: scheduler.Job.tasks:type_name -> scheduler.Task
	12, // 2: scheduler.Job.job_metadata:type_name -> scheduler.Job.JobMetadataEntry
	7,  // 3: scheduler.Task.container_config:type_name -> scheduler.ContainerSpec
	13, // 4: scheduler.Task.environment_variables:type_name -> scheduler.Task.EnvironmentVariablesEntry
	5,  // 5: scheduler.Task.resource_requirements:type_name -> scheduler.Resources
	6,  // 6: scheduler.Task.volume_mounts:type_name -> scheduler.Volume
	14, // 7: scheduler.ContainerSpec.driver_options:type_name -> scheduler.ContainerSpec.DriverOptionsEntry
	3,  // 8: scheduler.GetJobResponse.job:type_name -> scheduler.Job
	0,  // 9: scheduler.CentroSchedulerService.Heartbeat:input_type -> scheduler.HeartbeatRequest
	2,  // 10: scheduler.CentroSchedulerService.GetJob:input_type -> scheduler.GetJobRequest
	9,  // 11: scheduler.CentroSchedulerService.UpdateStatus:input_type -> scheduler.UpdateStatusRequest
	1,  // 12: scheduler.CentroSchedulerService.Heartbeat:output_type -> scheduler.HeartbeatResponse
	8,  // 13: scheduler.CentroSchedulerService.GetJob:output_type -> scheduler.GetJobResponse
	10, // 14: scheduler.CentroSchedulerService.UpdateStatus:output_type -> scheduler.UpdateStatusResponse
	12, // [12:15] is the sub-list for method output_type
	9,  // [9:12] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_agent_proto_init() }
func file_proto_agent_proto_init() {
	if File_proto_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_agent_proto_rawDesc), len(file_proto_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_agent_proto_goTypes,
		DependencyIndexes: file_proto_agent_proto_depIdxs,
		MessageInfos:      file_proto_agent_proto_msgTypes,
	}.Build()
	File_proto_agent_proto = out.File
	file_proto_agent_proto_goTypes = nil
	file_proto_agent_proto_depIdxs = nil
}
